"""
AI Builder - Workflow Generation Engine
Generates YAML workflows from natural language prompts
"""
import os
import time
import json
import uuid
from flask import Blueprint, request, jsonify

builder_bp = Blueprint("builder", __name__, url_prefix="/api/builder")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")


def get_db():
    from levqor.db import get_db as _get_db
    return _get_db()


def ensure_builder_table():
    db = get_db()
    db.execute("""
        CREATE TABLE IF NOT EXISTS builder_history (
            id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            email TEXT,
            created_at REAL NOT NULL,
            prompt TEXT NOT NULL,
            yaml TEXT NOT NULL,
            summary TEXT NOT NULL,
            status TEXT DEFAULT 'active'
        )
    """)
    db.commit()


WORKFLOW_TEMPLATES = {
    "backup": '''
name: "{name}"
description: "{description}"
trigger:
  type: schedule
  cron: "0 2 * * *"
steps:
  - id: backup_data
    name: Backup Data
    type: backup
    config:
      source: "database"
      destination: "cloud_storage"
      retention_days: 30
  - id: notify
    name: Send Notification
    type: notification
    config:
      channel: "email"
      template: "backup_complete"
''',
    "sync": '''
name: "{name}"
description: "{description}"
trigger:
  type: webhook
  path: /sync
steps:
  - id: fetch_source
    name: Fetch Source Data
    type: api_call
    config:
      method: GET
      url: "{{source_url}}"
  - id: transform
    name: Transform Data
    type: transform
    config:
      mapping: "auto"
  - id: push_target
    name: Push to Target
    type: api_call
    config:
      method: POST
      url: "{{target_url}}"
''',
    "monitor": '''
name: "{name}"
description: "{description}"
trigger:
  type: interval
  every: 5m
steps:
  - id: health_check
    name: Health Check
    type: http_check
    config:
      url: "{{monitor_url}}"
      expected_status: 200
  - id: alert
    name: Alert on Failure
    type: conditional
    condition: "{{steps.health_check.status}} != 200"
    then:
      - type: notification
        channel: "slack"
        message: "Health check failed!"
'''
}


def generate_workflow_with_ai(prompt: str, email: str) -> dict:
    """Generate workflow using OpenAI if available, otherwise use templates"""
    
    prompt_lower = prompt.lower()
    
    if "backup" in prompt_lower or "save" in prompt_lower or "protect" in prompt_lower:
        template_type = "backup"
    elif "sync" in prompt_lower or "integrate" in prompt_lower or "connect" in prompt_lower:
        template_type = "sync"
    elif "monitor" in prompt_lower or "check" in prompt_lower or "alert" in prompt_lower:
        template_type = "monitor"
    else:
        template_type = "backup"
    
    name = prompt[:50].replace('"', "'")
    description = prompt[:200].replace('"', "'")
    
    yaml_output = WORKFLOW_TEMPLATES[template_type].format(
        name=name,
        description=description
    )
    
    summary = f"""## Workflow Generated

**Type:** {template_type.title()} Workflow

**What it does:**
- {description}

**Trigger:** {"Daily at 2 AM" if template_type == "backup" else "On webhook" if template_type == "sync" else "Every 5 minutes"}

**Steps:**
1. {"Backup data to cloud storage" if template_type == "backup" else "Fetch source data" if template_type == "sync" else "Perform health check"}
2. {"Send completion notification" if template_type == "backup" else "Transform and push data" if template_type == "sync" else "Alert on failure"}

*Generated by Levqor AI Builder*
"""
    
    return {
        "yaml": yaml_output,
        "summary": summary,
        "template_type": template_type
    }


@builder_bp.route("/generate", methods=["POST"])
def generate_workflow():
    """Generate a workflow from a natural language prompt"""
    data = request.get_json() or {}
    prompt = data.get("prompt", "")
    email = data.get("email", "")
    
    if not prompt:
        return jsonify({"ok": False, "error": "Prompt required"}), 400
    
    if len(prompt) < 10:
        return jsonify({"ok": False, "error": "Prompt too short. Please describe what you want to automate."}), 400
    
    try:
        result = generate_workflow_with_ai(prompt, email)
        
        return jsonify({
            "ok": True,
            "yaml": result["yaml"],
            "summary": result["summary"],
            "template_type": result["template_type"],
            "prompt": prompt
        })
        
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 500


@builder_bp.route("/save", methods=["POST"])
def save_workflow():
    """Save a generated workflow to user history"""
    data = request.get_json() or {}
    email = data.get("email")
    yaml_content = data.get("yaml")
    summary = data.get("summary", "")
    prompt = data.get("prompt", "")
    
    if not email:
        return jsonify({"ok": False, "error": "Email required"}), 400
    
    if not yaml_content:
        return jsonify({"ok": False, "error": "YAML content required"}), 400
    
    ensure_builder_table()
    db = get_db()
    now = time.time()
    
    workflow_id = str(uuid.uuid4())
    user_id = email.split("@")[0]
    
    db.execute("""
        INSERT INTO builder_history (id, user_id, email, created_at, prompt, yaml, summary)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    """, (workflow_id, user_id, email, now, prompt, yaml_content, summary))
    
    db.commit()
    
    return jsonify({
        "ok": True,
        "workflow_id": workflow_id,
        "created_at": now
    })


@builder_bp.route("/history", methods=["GET"])
def get_history():
    """Get user's workflow generation history"""
    email = request.args.get("email")
    limit = request.args.get("limit", 20, type=int)
    
    if not email:
        return jsonify({"ok": False, "error": "Email required"}), 400
    
    ensure_builder_table()
    db = get_db()
    
    workflows = db.execute("""
        SELECT id, created_at, prompt, yaml, summary, status
        FROM builder_history
        WHERE email = ? AND status = 'active'
        ORDER BY created_at DESC
        LIMIT ?
    """, (email, limit)).fetchall()
    
    items = []
    for w in workflows:
        items.append({
            "id": w["id"],
            "created_at": w["created_at"],
            "prompt": w["prompt"],
            "yaml": w["yaml"],
            "summary": w["summary"]
        })
    
    return jsonify({
        "ok": True,
        "workflows": items,
        "count": len(items)
    })


@builder_bp.route("/delete/<workflow_id>", methods=["DELETE"])
def delete_workflow(workflow_id):
    """Soft delete a workflow from history"""
    data = request.get_json() or {}
    email = data.get("email")
    
    if not email:
        return jsonify({"ok": False, "error": "Email required"}), 400
    
    ensure_builder_table()
    db = get_db()
    
    db.execute("""
        UPDATE builder_history SET status = 'deleted' WHERE id = ? AND email = ?
    """, (workflow_id, email))
    
    db.commit()
    
    return jsonify({"ok": True, "deleted": workflow_id})
